account/urls.py
from django.urls import path
from .views import register_view, login_view, logout_view, contact_view
app_name = "account"

urlpatterns = [
    path("register/", register_view, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("contact/", contact_view, name="contact"),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from film.views import home__view, about__view, contact__view

urlpatterns = [
    path("", home__view, name= "home"),
    path("about", about__view, name= "about"),
    path("contact", contact__view, name= "contact"),
    path("account/", include("account.urls")),   
    path('admin/', admin.site.urls),
]

account/models.py
from django.db import models

# Create your models here.

film/models.py
from django.db import models

# Create your models here.

class Article(models.Model):
    author = models.ForeignKey("auth.User", on_delete=models.CASCADE)
    title = models.CharField(max_length=150, verbose_name="film_name")
    content = models.TextField(verbose_name="subject")
    created_date = models.DateTimeField(auto_now_add=True)
    
    
    def __str__(self):
        return f"{self.title} | {self.author}"
    

account/forms.py
from django import forms


class RegisterForm(forms.Form):
    username = forms.CharField(max_length=30, label="Username")
    password = forms.CharField(max_length=30, label="Password", widget=forms.PasswordInput)
    confirm = forms.CharField(max_length=30, label="Paswod confirm", widget=forms.PasswordInput)
    
    
    def clean(self):
        username = self.cleaned_data["username"]
        password = self.cleaned_data["password"]
        confirm = self.cleaned_data["confirm"]
        
        
        if password and confirm and password != confirm:
            raise forms.ValidationError("sifreler eyni deyil!!")
            
        values = {
            "username":username, 
            "password":password
        }
        return values
    
    

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30, label="Username")
    password = forms.CharField(max_length=30, label="Password", widget=forms.PasswordInput)

class PhoneForm(forms.Form):
    phone = forms.CharField(max_length=30, label="Phone number", widget=forms.TextInput)
            
    def clean_phone(self):
        phone = self.cleaned_data.get("phone")
        if not phone:
            raise forms.ValidationError("Phone number field is required")
        return phone

account/views.py
from django.contrib.auth import logout
from django.shortcuts import render, redirect
from .forms import RegisterForm, LoginForm, PhoneForm
from django.contrib.auth.models import User
from django.contrib.auth import login, authenticate

def register_view(request):
    form = RegisterForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        new_user = User(username=username)
        new_user.set_password(password)
        new_user.save()
        login(request, new_user)
        return redirect("home")

    context = {
        "form": form,
    }
    return render(request, "register.html", context)

def login_view(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password")
        user = authenticate(username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect("home")
    context = {
        "form": form,
    }
    return render(request, "login.html", context)

def logout_view(request):
    logout(request)
    return redirect("home")

def contact_view(request):
    form = PhoneForm(request.POST or None)
    if form.is_valid():
        phone = form.cleaned_data.get("phone")
    context = {
        "form": form,
    }
    return render(request, "contact.html", context)

film/views.py
from django.shortcuts import render
from .models import Article
def home__view(request):
    return render(request, 'index.html')


def about__view(request):
    return render(request, 'about.html')


def contact__view(request):
    return render(request, 'contact.html')

templates/about.html
{% extends "base.html"  %}

{% block page__title %}
     about page
{% endblock page__title %}




{% block body %}
<h2>about page</h2>
{% endblock body %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <title>
        {% block page__title %}
        {% endblock page__title %}
    </title>
</head>
<body>
<div class="navbar">
    <div class="nav__logo">
        <img src="{% static 'logo.png' %}">
    </div>
    <div class="nav__links">
        <ul>
            <li><a href="{% url  'home' %}">Home</a></li>
            <li><a href="{% url 'about' %}">About</a></li>
            <li><a href="{% url 'contact' %}">Contact</a></li>
            <li><a href="{% url 'account:login' %}">Login</a></li>
            <li><a href="{% url 'account:register' %}">Register</a></li>
            <li><a href="{% url 'account:logout' %}"><i class="fa-solid fa-right-from-bracket"></i></a></li>
        </ul>
    </div>
</div>
<div class="container">

    {% block body %}
    
    {% endblock body %}
</div>

</body>
</html>

templates/contact.html
{% extends "base.html"  %}

{% block page__title %}
contact page
{% endblock page__title %}




{% block body %}


<h2>contact page</h2>
<form method="post">
    {% csrf_token %}
    <label for="id_phone">Phone number:</label>
    {{ form.phone }}
    <button type="submit">nomre daxil et</button>
</form>

{% endblock body %}

templates/index.html
{% extends "base.html" %}
{% block page__title %}
MOVIES
{% endblock page__title %}



{% block body %}





<div class="films">
    <h1>Filmler Wikpedia</h1>
    <ul>
        {% for article in films %}
         <li>
            <h3>{{article.author}}</h3>
            <h4>{{article.title}}</h4>
            <p>{{article.content}}</p>
            <small>{{article.created_date}}</small>
         </li>
         <hr>
        {% endfor in %}
    </ul>
    </div>



{% endblock body %}

templates/login.html
{% extends "base.html"  %}

{% block page__title %}
  Login page
{% endblock page__title %}




{% block body %}
<h2>Login page</h2>



<form method="post" >
    {% csrf_token %}
   {{form.as_p}} <br>
   <button class="btn">daxil ol</button>
</form>

{% endblock body %}

templates/register.html
{% extends "base.html"  %}


{% block page__title %}
  Register page  
{% endblock page__title %}

{% block body %}
<h2>Register page</h2>

<form method="post" >
    {% csrf_token %}
   {{form.as_p}} <br>
   <button class="btn">qeydiyatdan kec</button>
</form>


{% endblock body %}